site_name: Distributed Assertion Management Framework
nav:
    - Home: 'index.md'
    - Design:
      - DAMF Formats: 'damf-formats.md'
      - Processes: 'damf-processes.md'
    - Dispatch: 'dispatch.md'
    - 'Edge Systems':
        - 'Abella DAMF': 'abella.md'
        - 'Î»Prolog': 'lprolog.md'
    - 'Example': 'example-walkthrough.md'
theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/lightning-bolt-outline
        name: :Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/lightning-bolt
        name: Switch to light mode
  font:
    text:  M PLUS Rounded 1c
    code: Roboto Mono
  logo: assets/logo/logo.png
  favicon: assets/logo/favicon.ico
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - toc.follow
    - navigation.top
    - navigation.expand
    - navigation.footer
extra_css:
  - assets/css/extra.css
  - assets/css/collapsible.css
extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/distributed-assertions
      name: DAMF on github
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences
  - smarty
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: Copyright &copy; 2023 . <a href="https://innofarah.com" target="_blank">Farah Al Wardani</a>, 
           <a href="https://chaudhuri.info" target="_blank">Kaustuv Chaudhuri</a>, 
           and <a href="https://www.lix.polytechnique.fr/~dale/" target="_blank">Dale Miller</a>